#! /usr/bin/env python 

import os, sys
from distutils.dir_util import copy_tree
from shutil import copymode


ORG_WEB_HOME = os.environ.get('ORG_WEB_HOME') if os.environ.get('ORG_WEB_HOME') is not None else os.path.join( os.getenv('HOME'), 'local', 'org-web' )

copy_to_here = os.getcwd()

if not 'index.org' in os.listdir( ORG_WEB_HOME ):
   sys.exit( '%s does not seem to be org-web home' )

copy_tree( ORG_WEB_HOME, copy_to_here )
copymode( os.path.join( ORG_WEB_HOME, 'css' ), os.path.join( copy_to_here, 'css' ) )
